* TescoRb
** Usage Examples:

#+BEGIN_SRC ruby
client = TescoRb.new(YOUR_API_KEY)

# To search for items:
client.item.search('bananas')
client.item.search('bananas', limit: 10)
client.item.search('bananas', limit: 10, offset: 10)

# To search for Shops:
client.store(near: 'SW5 4YY')
client.store(near: 'SW5 4YY', limit: 5)
client.store(filter: 'isoCountryCode:GB AND category:Store AND facilities:DBT')
#+END_SRC


*** Todos
    - `client.item.search('bananas')` syntax; add `.search` method
      - This would involve creating new 'items' holding class (currently just an Array)




  # TescoRb

  Welcome to your new gem! In this directory, you'll find the files you need to be able to package up your Ruby library into a gem. Put your Ruby code in the file `lib/tesco_rb`. To experiment with that code, run `bin/console` for an interactive prompt.

  TODO: Delete this and the text above, and describe your gem

  ## Installation

  Add this line to your application's Gemfile:

  ```ruby
  gem 'tesco_rb'
  ```

  And then execute:

      $ bundle

  Or install it yourself as:

      $ gem install tesco_rb

  ## Usage

  TODO: Write usage instructions here

  ## Development

  After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake test` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

  To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

  ## Contributing

  Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/tesco_rb. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [Contributor Covenant](http://contributor-covenant.org) code of conduct.


  ## License

  The gem is available as open source under the terms of the [MIT License](http://opensource.org/licenses/MIT).
